# Generated by Django 2.1.7 on 2019-03-04 08:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_auto_20190304_1447'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='subject',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='topic',
            name='starter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='topics', to=settings.AUTH_USER_MODEL),
        ),
    ]
