# Generated by Django 2.1.7 on 2019-03-04 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0005_auto_20190304_1617'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='title',
            new_name='subject',
        ),
    ]
